### ISSUE TITLE
机器人改转发

### ISSUE THREAD

**Issue by big101** [ccding/wechat-forwarding#1]
这是微信机器人，想改成转发消息到群能具体写个描述吗？或者写到README里面，感谢。

**Comment by ccding** [comment]
改 config 然后启动就可以了

**Comment by big101** [comment]
您好，可能我水平还不够，能添加些注释吗？例如G1 2 3和groups等重要变量的作用，十分感谢！




------------------ 原始邮件 ------------------
发件人: "Cong Ding"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 晚上10:32
收件人: "ccding/wechat-forwarding"<wechat-forwarding@noreply.github.com>;
抄送: "柳"<35031550@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ccding/wechat-forwarding] 机器人改转发 (#1)




改 config 然后启动就可以了

**Comment by ccding** [comment]
G1 G2 等替换成群名
